# config.yaml
time_seed: 0
output_folder: "train_CIFAR10_noise"
workers: 32

#noise "cifar-10"
dataset: "cifar-10"
remark: ""

# train
batch: 256
epochs: 200
flow_modules: '64-64-64-64-64'
cond_size: 64
lr: 1.0e-2
encoder_lr: 1.0e-3
inputDim: 10 # for image N_classes

# cos, ""
lr_scheduler: "cos"

# noise
algorithm: "flow"
noise_type: 'sym' #sym  0.2 0.5 0.8 #asym  0.2 0.3 0.4
percent: 0.5
ssl: true
y_noise_std: 0.2
lambda_reg: 25.

# encoder
pretrain_encoder: ""
pretrain_flow: ""
fix_encoder: false
blur: true

# auto_drop
auto_drop: true
